let str ='hi its sindhuja';
        str1= str.toUpperCase();
        console.log(str1);
        str2 = str.toLowerCase();
        console.log(str2);
        str3 = str.charAt(3);
        console.log(str3);
        str4 = str.indexOf('si',3);
        console.log(str4);
        str5 = str.concat(' hello')
        console.log(str5);
        str6 = str.includes('ja',4);
        console.log(str6);
        str7 = str.replace('hi','hello');
        console.log(str7);
        str8 = str.search('ind');
        console.log(str8);
        str9 =str.trim();
        console.log(str9);
        str10 = str.substr(0,3);
        console.log(str10);
        str11 = str.split('u');
        console.log(str11);
        str12 = str.split('j',2);
        console.log(str12);
console.log('==========================================');
let stri ='i love food';
        str1= stri.toUpperCase();
        console.log(str1);
        str2 = stri.toLowerCase();
        console.log(str2);
        str3 = stri.charAt(3);
        console.log(str3);
        str4 = stri.indexOf('ve',3);
        console.log(str4);
        str5 = stri.concat(' very much')
        console.log(str5);
        str6 = stri.includes('ja',4);
        console.log(str6);
        str7 = stri.replace('love','like');
        console.log(str7);
        str8 = stri.search('od');
        console.log(str8);
        str9 =stri.trim();
        console.log(str9);
        str10 = stri.substr(0,3);
        console.log(str10);
        str11 = stri.split('e');
        console.log(str11);
        str12 = stri.split('e',2);
        console.log(str12);
        console.log('===============================================');
        let st ='i love sleeping';
        str1= st.toUpperCase();
        console.log(str1);
        str2 = st.toLowerCase();
        console.log(str2);
        str3 = st.charAt(3);
        console.log(str3);
        str4 = st.indexOf('si',3);
        console.log(str4);
        str5 = st.concat(' , shopping')
        console.log(str5);
        str6 = st.includes('pi',4);
        console.log(str6);
        str7 = st.replace('hi','hello');
        console.log(str7);
        str8 = st.search('ov');
        console.log(str8);
        str9 =st.trim();
        console.log(str9);
        str10 = st.substr(0,3);
        console.log(str10);
        str11 = st.split('v');
        console.log(str11);
        str12 = st.split('p',2);
        console.log(str12);
        console.log('=========================================================')
        let stg ='im learning javascript';
        str1= stg.toUpperCase();
        console.log(str1);
        str2 = stg.toLowerCase();
        console.log(str2);
        str3 = stg.charAt(3);
        console.log(str3);
        str4 = stg.indexOf('sc',3);
        console.log(str4);
        str5 = stg.concat(' hi')
        console.log(str5);
        str6 = stg.includes('ja',4);
        console.log(str6);
        str7 = stg.replace('javascript','html');
        console.log(str7);
        str8 = stg.search('ea');
        console.log(str8);
        str9 =stg.trim();
        console.log(str9);
        str10 = stg.substr(0,3);
        console.log(str10);
        str11 = stg.split('a');
        console.log(str11);
        str12 = stg.split('j',2);
        console.log(str12);
        console.log('=======================================================')
        let stv ='today is a beautiful day';
        str1= stv.toUpperCase();
        console.log(str1);
        str2 = stv.toLowerCase();
        console.log(str2);
        str3 = stv.charAt(3);
        console.log(str3);
        str4 = stv.indexOf('si',3);
        console.log(str4);
        str5 = stv.concat(' hello')
        console.log(str5);
        str6 = stv.includes('ja',4);
        console.log(str6);
        str7 = stv.replace('today','everyday');
        console.log(str7);
        str8 = stv.search('if');
        console.log(str8);
        str9 =stv.trim();
        console.log(str9);
        str10 = stv.substr(0,3);
        console.log(str10);
        str11 = stv.split('u');
        console.log(str11);
        str12 = stv.split('u',2);
        console.log(str12);
        console.log('=======================================================')
        let stl ='i love to do shopping';
        str1= stl.toUpperCase();
        console.log(str1);
        str2 = stl.toLowerCase();
        console.log(str2);
        str3 = stl.charAt(3);
        console.log(str3);
        str4 = stl.indexOf('o',3);
        console.log(str4);
        str5 = stl.concat(' hello')
        console.log(str5);
        str6 = stl.includes('in',4);
        console.log(str6);
        str7 = stl.replace('love','like');
        console.log(str7);
        str8 = stl.search('if');
        console.log(str8);
        str9 =stl.trim();
        console.log(str9);
        str10 = stl.substr(0,3);
        console.log(str10);
        str11 = stl.split('v');
        console.log(str11);
        str12 = stl.split('p',2);
        console.log(str12);
        console.log('=======================================================')
        let stn ='i moved to bangalore';
        str1= stn.toUpperCase();
        console.log(str1);
        str2 = stn.toLowerCase();
        console.log(str2);
        str3 = stn.charAt(3);
        console.log(str3);
        str4 = stn.indexOf('si',3);
        console.log(str4);
        str5 = stn.concat(' hello')
        console.log(str5);
        str6 = stn.includes('hg',4);
        console.log(str6);
        str7 = stn.replace('moved','shifted');
        console.log(str7);
        str8 = stn.search('ve');
        console.log(str8);
        str9 =stn.trim();
        console.log(str9);
        str10 = stn.substr(0,3);
        console.log(str10);
        str11 = stn.split('a');
        console.log(str11);
        str12 = stn.split('b',2);
        console.log(str12);
        console.log('=======================================================')
        let stm ='go green';
        str1= stm.toUpperCase();
        console.log(str1);
        str2 = stm.toLowerCase();
        console.log(str2);
        str3 = stm.charAt(3);
        console.log(str3);
        str4 = stm.indexOf('gr',3);
        console.log(str4);
        str5 = stm.concat(' hello')
        console.log(str5);
        str6 = stm.includes('re',4);
        console.log(str6);
        str7 = stm.replace('green','blue');
        console.log(str7);
        str8 = stm.search('ee');
        console.log(str8);
        str9 =stm.trim();
        console.log(str9);
        str10 = stm.substr(0,3);
        console.log(str10);
        str11 = stm.split('r');
        console.log(str11);
        str12 = stm.split('r',2);
        console.log(str12);
        console.log('=======================================================')
        let sth ='hard work is the key to success';
        str1= sth.toUpperCase();
        console.log(str1);
        str2 = sth.toLowerCase();
        console.log(str2);
        str3 = sth.charAt(3);
        console.log(str3);
        str4 = sth.indexOf('ey',3);
        console.log(str4);
        str5 = sth.concat(' hello')
        console.log(str5);
        str6 = sth.includes('ey',4);
        console.log(str6);
        str7 = sth.replace('success','failure');
        console.log(str7);
        str8 = sth.search('if');
        console.log(str8);
        str9 =sth.trim();
        console.log(str9);
        str10 = sth.substr(0,3);
        console.log(str10);
        str11 = sth.split('u');
        console.log(str11);
        str12 = sth.split('u',2);
        console.log(str12);
        console.log('=======================================================')
        let stu ='i love reading';
        str1= stu.toUpperCase();
        console.log(str1);
        str2 = stu.toLowerCase();
        console.log(str2);
        str3 = stu.charAt(3);
        console.log(str3);
        str4 = stu.indexOf('ea',3);
        console.log(str4);
        str5 = stu.concat(' hello')
        console.log(str5);
        str6 = stu.includes('ea',4);
        console.log(str6);
        str7 = stu.replace('love','like');
        console.log(str7);
        str8 = stu.search('ea');
        console.log(str8);
        str9 =stu.trim();
        console.log(str9);
        str10 = stu.substr(0,3);
        console.log(str10);
        str11 = stu.split('e');
        console.log(str11);
        str12 = stu.split('r',2);
        console.log(str12);
        console.log('=======================================================')
        
